# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a13123bfc459d3cb09cb48100e2d95a83ccfb13e01580786b1d9bab81bdbbbe7db8a18bed2ba9937d8c7a8afe96aaaff0efc4fa3f24f209331d709f4e4e7aa
  pusher_host: "localhost:4000"
  org_id: acme-inc
  app_key: 0221981c-cdef-11e6-beea-28cfe91ef193
  secret_token: 4036de82-c6ab-11e6-9a53-28cfe91ef193

test:
  secret_key_base: 152504be15a285e2015fa51990d075ea5a9936fb7532eee75a00a812211b2854df607d0713737dc1b88e30dd0ec9e2eae94f0b86af5518781640d1b2c2d92fb0
  pusher_host: "localhost:4000"
  org_id: acme-inc
  app_key: 0221981c-cdef-11e6-beea-28cfe91ef193
  secret_token: 4036de82-c6ab-11e6-9a53-28cfe91ef193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pusher_host: <%= ENV['PUSHER_LITE_HOST'] %>
  org_id: <%= ENV['PUSHER_LITE_ORGANIZATION'] %>
  app_key: <%= ENV["PUSHER_LITE_APP_KEY"] %>
  secret_token: <%= ENV["PUSHER_LITE_SECRET_TOKEN"] %>
