# This file is a template, and might need editing before it works on your project.
image: codeminer42/ci-elixir:1.3

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest

cache:
  key: ex_pusher_lite
  paths:
    - .ci_cache/
    - .ci_deps/
    - .ci_npm_cache/

variables:
  MIX_ENV: 'test'
  DATABASE_URL: postgresql://postgres:@postgres
  CI: '1'

before_script:
  - mkdir -p .ci_cache/
  - mkdir -p .ci_deps/
  - mkdir -p _build/
  - cp -R .ci_cache/ _build/
  - cp -R .ci_deps/ deps/
  - mix local.hex --force
  - mix deps.clean --unlock --unused
  - mix deps.get
  - npm config set cache $(pwd)/.ci_npm_cache
  - npm install --loglevel warn
  - cp -f config/test.exs.gitlab config/test.exs
  - MIX_ENV=test mix do ecto.create, ecto.migrate

after_script:
  - cp -R _build/ .ci_cache/
  - cp -R deps/ .ci_deps/

test:
  script:
    - mix test
